site_name: FRDM-MCXA153 Example projects (for SDK v2.14.2)
docs_dir: 'frdm-mcxa153'

theme:
  name: readthedocs

use_directory_urls: false

nav:
  - Introduction: index.md
  - 01 Getting started: projects/getting_started/README.md
  - 02 CMSIS: docs/cmsis.md
  - 03 General purpose output: projects/general_purpose_output/README.md
  - 04 General purpose input: projects/general_purpose_input/README.md
  - 05 Core clock: docs/core_clock.md
  - 06 SysTick: projects/systick/README.md
  - 07 Low-Power timer: projects/lptmr/README.md
  - 08 Low-Power UART - polling: projects/lpuart_polling/README.md
  - 09 Low-Power UART - interrupt: projects/lpuart_interrupt/README.md
  - 10 Standard Counter or Timer - match interrupt: projects/ctimer_match_interrupt/README.md
  - 11 Standard Counter or Timer - PWM: projects/ctimer_pwm/README.md
  - 12 Flex PWM - edge aligned: projects/flexpwm_edge_aligned/README.md
  - __ USB HID: projects/usb_hid/README.md